eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    organizationservice: /organ/**
    licensingservice: /licen/**

spring:
  zipkin:
    baseUrl:  http://localhost:9411
