server:
  port: 8888
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          #          search-locations: file:///Users/fenghaiyu/workspace\springboottest\confsvr\src\main\resources\config\licensingservice
          uri: https://github.com/fhyfhy17/config-repo
          search-paths: licensingservice
